//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSRC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Setting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSRC.Setting", typeof(Setting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Google\Chrome\Application\chrome.exe.
        /// </summary>
        public static string chromApp {
            get {
                return ResourceManager.GetString("chromApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider = Microsoft.ACE.OLEDB.12.0;Data Source =D:\WORK\_Compuco\ORM-tat\New folder\orm 2023\Orm setting Access\OrmNetFrame\AccssDb\Db\db.mdb.
        /// </summary>
        public static string CNSTR {
            get {
                return ResourceManager.GetString("CNSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source =D:\WORK\_Compuco\ORM-tat\New folder\orm 2023\Orm setting Access\OrmNetFrame\AccssDb\Db\db.mdb.
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Desktop-1401\Projects Desktop-1401\Visual Studio 2015-projects\desk-1400-apps\Win App TNT\code parcel\New Text Document.txt.
        /// </summary>
        public static string DefaultPath {
            get {
                return ResourceManager.GetString("DefaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GlobalPath {
            get {
                return ResourceManager.GetString("GlobalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d:\.
        /// </summary>
        public static string InitialPath {
            get {
                return ResourceManager.GetString("InitialPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider = Microsoft.ACE.OLEDB.12.0;.
        /// </summary>
        public static string PrvdrAce {
            get {
                return ResourceManager.GetString("PrvdrAce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider = Microsoft.JET.OLEDB.4.0;.
        /// </summary>
        public static string PrvdrJet {
            get {
                return ResourceManager.GetString("PrvdrJet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tntiran.com/track-fa.php?cn=.
        /// </summary>
        public static string strUrl {
            get {
                return ResourceManager.GetString("strUrl", resourceCulture);
            }
        }
    }
}
